dist: xenial

language: php

php:
  - 7.1
  - 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --dev

script:

  # PSR-2
  - ./vendor/bin/phpcs --standard=psr2 -n src/

  # PhpUnit - whole project
  - mkdir -p build/logs && ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

  # League/Uri isolated factory test
  - composer rem --dev league/uri guzzlehttp/psr7 zendframework/zend-diactoros
  - composer req --dev --prefer-dist league/uri ^5.0
  - phpunit tests/UriFactoryTest.php

  # Zend Diactoros isolated ffactory test
  - composer rem --dev league/uri guzzlehttp/psr7 zendframework/zend-diactoros
  - composer req --dev --prefer-dist zendframework/zend-diactoros
  - phpunit tests/UriFactoryTest.php

  # Guzzle PSR-7 isolated ffactory test
  - composer rem --dev league/uri guzzlehttp/psr7 zendframework/zend-diactoros
  - composer req --dev --prefer-dist guzzlehttp/psr7
  - phpunit tests/UriFactoryTest.php

after_script:
  - php vendor/bin/coveralls -v
