dist: xenial

language: php

php:
  - '8.0'
  - '8.1'
  - '8.2'
  - 'nightly'


matrix:
  allow_failures:
    - php: 'nightly'


before_script:
  - travis_retry composer self-update
  - travis_retry composer global require hirak/prestissimo
  - travis_retry composer install --no-interaction --prefer-dist --dev

script:

  # PSR-2
  - ./vendor/bin/phpcs --standard=psr2 -n src/

  # PhpUnit - whole project
  - mkdir -p build/logs && ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

  # League/Uri isolated factory test
  - composer rem --dev league/uri nyholm/psr7 guzzlehttp/psr7 ringcentral/psr7
  - composer req --dev --prefer-dist league/uri:^5.0
  - ./vendor/bin/phpunit tests/UriFactoryTest.php

  # Guzzle PSR-7 isolated ffactory test
  - composer rem --dev league/uri nyholm/psr7 guzzlehttp/psr7 ringcentral/psr7
  - composer req --dev --prefer-dist guzzlehttp/psr7
  - ./vendor/bin/phpunit tests/UriFactoryTest.php

  # Nyholm PSR-7 isolated ffactory test
  - composer rem --dev league/uri nyholm/psr7 guzzlehttp/psr7 ringcentral/psr7
  - composer req --dev --prefer-dist nyholm/psr7
  - ./vendor/bin/phpunit tests/UriFactoryTest.php

  # Nyholm PSR-7 isolated ffactory test
  - composer rem --dev league/uri nyholm/psr7 guzzlehttp/psr7 ringcentral/psr7
  - composer req --dev --prefer-dist ringcentral/psr7
  - ./vendor/bin/phpunit tests/UriFactoryTest.php

after_script:
  - php vendor/bin/php-coveralls -v
