dist: xenial

language: php

php:
  - 7.1
  - 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/bin/phpcs --standard=psr2 -n src/
  - composer rem --dev league/uri guzzlehttp/psr7 zendframework/zend-diactoros
  - composer req --dev --prefer-dist league/uri && phpunit tests/UriFactoryTest.php
  - composer rem --dev league/uri guzzlehttp/psr7 zendframework/zend-diactoros
  - composer req --dev --prefer-dist zendframework/zend-diactoros && phpunit tests/UriFactoryTest.php
  - composer rem --dev league/uri guzzlehttp/psr7 zendframework/zend-diactoros
  - composer req --dev --prefer-dist guzzlehttp/psr7 && phpunit tests/UriFactoryTest.php
  - composer req --dev --prefer-dist league/uri guzzlehttp/psr7 zendframework/zend-diactoros
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
